apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mwh8goqet-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mwh8goqet-nodejs 
  name: mwh8goqet-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: mwh8goqet-nodejs 
